apiVersion: apps/v1
kind: Deployment
metadata:
  name: tke-anp-server
  namespace: tke
spec:
  selector:
    matchLabels:
      app: tke-anp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: tke-anp-server
    spec:
      containers:
      - name: tke-anp-server
        image: huxl/tke-anp-server-amd64:1.0
        imagePullPolicy: IfNotPresent 
        resources:
          requests:
            cpu: 2
            memory: 200Mi
          limits:
            cpu: 4
            memory: 400Mi
        command: [ "/proxy-server"]
        args: [
          "--logtostderr=false",
          "--log-file-max-size=0",
          "--uds-name=/tmp/konnectivity-server.socket",
          "--cluster-cert=/etc/tunnel/pki/tls.crt",
          "--cluster-key=/etc/tunnel/pki/tls.key",
          "--server-port=0",
          "--agent-port=8091",
          "--health-port=8092",
          "--admin-port=8093",
          "--keepalive-time=1h",
          "--mode=http-connect",
          ]
        volumeMounts:
        - name: pki
          mountPath: "/etc/tunnel/pki/"
          readOnly: true
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 8092
            path: /healthz
          initialDelaySeconds: 10
          timeoutSeconds: 60
        ports:
        - name: serverport
          containerPort: 8090
        - name: agentport
          containerPort: 8091
        - name: healthport
          containerPort: 8092
        - name: adminport
          containerPort: 8093
      volumes:
      - name: pki
        secret:
          secretName: tke-anp-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: tke-anp-server
  namespace: tke
  labels:
    app: tke-anp-server
spec:
  type: NodePort
  selector:
    app: tke-anp-server
  ports:
  - port: 8091
    targetPort: 8091
    nodePort: 32500
