apiVersion: apps/v1
kind: Deployment
metadata:
  name: tke-anp-agent
  namespace: tke
spec:
  selector:
    matchLabels:
      app: tke-anp-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: tke-anp-agent
    spec:
      containers:
      - name: tke-anp-agent
        image: huxl/tke-anp-agent-amd64:1.0
        imagePullPolicy: IfNotPresent 
        resources:
          requests:
            cpu: 2
            memory: 200Mi
          limits:
            cpu: 4
            memory: 400Mi
        command: [ "/proxy-agent"]
        args: [
          "--logtostderr=true",
          "--ca-cert=/etc/tunnel/pki/ca.crt",
          "--agent-cert=/etc/tunnel/pki/tls.crt",
          "--agent-key=/etc/tunnel/pki/tls.key",
          "--proxy-server-host=132.232.31.102",
          "--proxy-server-port=32500",
          ]
        volumeMounts:
        - name: pki
          mountPath: "/etc/tunnel/pki/"
          readOnly: true
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 8093
            path: /healthz
          initialDelaySeconds: 10
          timeoutSeconds: 60
        ports:
        - name: healthport
          containerPort: 8093
        - name: adminport
          containerPort: 8094
        - name: fowardport
          containerPort: 8088
      volumes:
      - name: pki
        secret:
          secretName: tke-anp-agent-tls
---
apiVersion: v1
kind: Service
metadata:
  name: tke-anp-agent
  namespace: tke
  labels:
    app: tke-anp-agent
spec:
  selector:
    app: tke-anp-agent
  ports:
  - port: 8094
    targetPort: 8094
    name: adminport
  - port: 8088
    targetPort: 8088
    name: fowardport
